### ISSUE TITLE
add ability to fix broken upgrades

### ISSUE THREAD

**Issue by bpmct** [ericpaulsen/cdr-cs#1]
My upgrade often breaks, requiring me to follow these steps: https://coder.com/docs/setup/updating#fixing-a-failed-upgrade

I'd love if this script could do that here. I can get to this later this week. I need my Coder workspace tonight for some demos so I'm creating this now so I can reference later. If you want to give this a go before I do, feel free.

- [x] Stage 1: Detect if an upgrade fails, and point the user to the docs to fix
- [x] Stage 2 (overkill?): Additionally, add and tell user to run `./upgrade.sh --fix` to attempt to these commands automatically
    - should potentially wait ~20 seconds after helm uninstall to ensure all resources are destroyed, or even smarter: check periodically with a loop
    - can save helm values to /tmp/coder-values.yaml and then delete after using it in `helm upgrade`
    - fetch latest ingress IP and tell the user they may need to update their DNS
    
see value of command command, or if it fails: https://askubuntu.com/a/29379

add arguments: https://www.baeldung.com/linux/use-command-line-arguments-in-bash-script

**Comment by ericpaulsen** [comment]
Stage 1 completed. As for Stage 2, I don't think it's overkill. I see it as a good challenge. Will get started on this by end of week.
